### ISSUE TITLE
App not loading data/estimates

### ISSUE THREAD

**Issue by seabbs** [BDI-pathogens/LocalCovidTracker#2]
App is not loading results or estimates for me. Tried to load 3 times over 30 minutes. May be a user load issue.

**Comment by MichelleKendall** [comment]
Hi, thanks for flagging this. I see there was a surge in users this morning which it couldn't handle. I've tweaked the performance parameters to hopefully better handle surges in future but do let me know if there continue to be problems as I can tune it further and / or look at ways of reducing / segmenting the content.

**Comment by seabbs** [comment]
No problem at all. 

I am now seeing some kind of crash when trying to load. 


![Screenshot 2021-02-09 at 15 16 25](https://user-images.githubusercontent.com/20317649/107384350-c7fb6e00-6ae9-11eb-8ffa-1f14728f0b88.png)

Its frozen like this to be clear.

**Comment by MichelleKendall** [comment]
Sorry for the inconvenience with loading problems yesterday. I've just changed a few things which I hope will speed it up. When convenient, would you mind checking if it's improved at your end, please? Thanks.

**Comment by seabbs** [comment]
Yes looks good!

**Comment by MichelleKendall** [comment]
Excellent, thanks!
